import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import dynamic from "next/dynamic";
import ReactToastifyProvider from "@/utils/providers/ReactToastifyProvider/ReactToastifyProvider";
import ReactReduxProvider from "@/utils/providers/ReactReduxProvider/ReactReduxProvider";
import ReactReduxParsistProvider from "@/utils/providers/ReactReduxParsistProvider/ReactReduxParsistProvider";
const ReactQueryProvider = dynamic(
  () => import("@/utils/providers/ReactQueryProvider/ReactQueryProvider"),
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GARAGE-HERO Test",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body>
        <ReactReduxProvider>
          <ReactReduxParsistProvider>
            <ReactQueryProvider>
              <ReactToastifyProvider>{children}</ReactToastifyProvider>
            </ReactQueryProvider>
          </ReactReduxParsistProvider>
        </ReactReduxProvider>
      </body>
    </html>
  );
}
